// Generated by CoffeeScript 1.6.2
(function() {
  var assert;

  mocha.setup('bdd');

  assert = function(expr, msg) {
    if (msg == null) {
      msg = 'failed';
    }
    if (!expr) {
      throw new Error(msg);
    }
  };

  describe('文字単体', function() {
    return it('zen2han', function() {
      var zen;

      zen = '　ｇ　／';
      console.log(normalizr(zen, 'numeric'));
      return assert((normalizr(zen, 'zen2han')) === ' g /');
    });
  });

  mocha.run();

}).call(this);
