// Generated by CoffeeScript 1.6.2
/*
全角 => 半角
*/


(function() {
  var convert, filterNaN, normalizr, zen2han, _ref;

  zen2han = function(zen) {
    var han;

    han = zen.replace(/[Ａ-Ｚａ-ｚ０-９！＂＃＄％＆＇（）＊＋，－．／：；＜＝＞？＠［＼］＾＿｀｛｜｝～]/g, function(c) {
      return String.fromCharCode(c.charCodeAt(0) - 0xFEE0);
    });
    return han.split('　').join(' ');
  };

  /*
  数字のみ
  */


  filterNaN = function(nan) {
    return nan.replace(/\D/g, '');
  };

  /*
  変換ハンドリング
  */


  convert = function(str, condition) {
    var c, conditions, _i, _len;

    str = '' + str;
    conditions = condition instanceof Array ? condition : [condition];
    for (_i = 0, _len = conditions.length; _i < _len; _i++) {
      c = conditions[_i];
      switch (c) {
        case 'zen2han':
          str = zen2han(str);
          break;
        case 'numeric':
          str = filterNaN(str);
          break;
        default:
          if (typeof c === 'function') {
            str = c(str);
          }
      }
    }
    return str;
  };

  /*
  インターフェース
  */


  normalizr = function(obj, opts) {
    var condition, key, result, value;

    if (typeof obj === 'string') {
      return convert(obj, opts);
    } else {
      result = {};
      for (key in obj) {
        value = obj[key];
        condition = opts[key];
        if (condition != null) {
          result[key] = convert(value, condition);
        } else {
          result[key] = value;
        }
      }
      return result;
    }
  };

  /*
  export
  */


  if ((_ref = (function() {
    if (typeof self !== 'undefined') {
      return self;
    }
    if (typeof window !== 'undefined') {
      return window;
    }
    if (typeof global !== 'undefined') {
      return global;
    }
    return null;
  })()) != null) {
    _ref.normalizr = normalizr;
  }

}).call(this);
